config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins
  resources :tracks
  get 'pages/sgk'

  get 'pages/ficr'

  get 'pages/adria'

  get 'pages/miscela'

  get 'pages/rapporti'

  get 'pages/livetiming'

  root 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track.rb
class Track < ApplicationRecord

	has_attached_file :cover, styles: { large: "600x>", medium: "500x>", thumb: "100x100>" }, default_url: "/assets/missing.jpg"
  	validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  	#inizio modifica search bar
	def self.search(search)
		where("zone LIKE ?", "%#{search}%") 
	end
	#fine modifica search bar

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def livetiming
  end

  def ficr
  end

  def adria
  end

  def miscela
  end

  def rapporti
  end

  def sgk
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]

  # GET /tracks
  # GET /tracks.json
  def index
    @tracks = Track.all

    #inizio modifiche per search bar
    if params[:search]
    @tracks = Track.search(params[:search]).order("created_at DESC")
    else
      @tracks = Track.all.order('created_at DESC')
    end
    #fine modifiche per search bar
    
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
  end

  # GET /tracks/1/edit
  def edit
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_params
      params.require(:track).permit(:name, :city, :address, :region, :zone, :mag_band, :length, :description, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper

end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/_header.html.erb
  <header class="navbar-fixed">

      <!-- Navbar desktop -->
    <nav class="grey darken-4" role="navigation">
      <div class="nav-wrapper container">
        <%= link_to image_tag("logo.svg", :alt => "EVG Motorsport", :class => "brand-logo"), root_path %>

        <ul id="nav-desktop" class="right hide-on-med-and-down white-text">
          <li><%= link_to icon('home fa-2x'), 'http://www.evgmotorsport.com', :class => "white-text", :title => "Home" %></li>
          <li><%= link_to icon('facebook-square fa-2x'), 'https://www.facebook.com/evgmotorsport', :class => "white-text", :title => "Facebook" %></li>
          <li><%= link_to icon('twitter-square fa-2x'), 'https://twitter.com/EVG_MotorSport', :class => "white-text", :title => "Twitter" %></li>
          <li><%= link_to icon('instagram fa-2x'), 'https://www.instagram.com/evgmotorsport/', :class => "white-text", :title => "Instagram" %></li>
          <li><%= link_to icon('envelope fa-2x'), 'mailto:info@evgmotorsport.com', :class => "white-text", :title => "Mail" %></li>
        </ul>

        <!-- Navbar mobile -->
        <ul id="nav-mobile" class="side-nav grey darken-4">
          <li><%= link_to icon('home fa-3x white-text'), 'http://www.evgmotorsport.com', :title => "Home", :class => "side-nav-home side-nav-icons" %></li>
          <li><%= link_to icon('facebook-square fa-3x white-text'), 'https://www.facebook.com/evgmotorsport', :title => "Facebook", :class => "side-nav-icons" %></li>
          <li><%= link_to icon('twitter-square fa-3x white-text'), 'https://twitter.com/EVG_MotorSport', :title => "Twitter", :class => "side-nav-icons" %></li>
          <li><%= link_to icon('instagram fa-3x white-text'), 'https://www.instagram.com/evgmotorsport/', :title => "Instagram", :class => "side-nav-icons" %></li>
          <li><%= link_to icon('envelope fa-3x white-text'), 'mailto: info@evgmotorsport.com', :title => "Mail", :class => "side-nav-icons" %></li>
          <li class="side-nav-credits">
              © 2016 
              <%= link_to 'EVG Motorsport', 'http://www.evgmotorsport.com', :class => "light-blue-text text-darken-3", :title => "EVG MotorSport" %> 
              All rights reserved. 
              <br><br> 
              <% if admin_signed_in? %>
                <%= link_to 'Log Out', destroy_admin_session_path, method: :delete, :class => "light-blue-text text-darken-3", :title => "Administration Log-out" %>
              <% else %>
                <%= link_to 'Admin', new_admin_session_path, :class => "light-blue-text text-darken-3", :title => "Administration Log-in" %>
              <% end %>
          </li>
        </ul>

        <a href="#" data-activates="nav-mobile" class="button-collapse right"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
      </div>
    </nav> 
  </header>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>EVG Motorsport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Google Font -->
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Nova+Flat|Press+Start+2P|Doppio+One" %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/icon?family=Material+Icons" %>

    <!-- Google Analytics -->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-66129212-1', 'auto');
      ga('send', 'pageview');

    </script>

  </head>

  <body>

  	<%= render "layouts/header" %>

  	<main>

    	<%= yield %>

	  </main>

  </body>

  	<script>

      $(document).ready(function(){
      
        // Sidebar
        $('.button-collapse').sideNav({
            menuWidth: 100, // Default is 240
            edge: 'right', // Choose the horizontal origin
            closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
          }
        );

        $('.collapsible').collapsible();

        $('select').material_select();

        // Hide sideNav
        $('.button-collapse').sideNav('hide');
        // Show sideNav
        //$('.button-collapse').sideNav('show');

        // Dropdown
        $('.dropdown-button').dropdown({
             inDuration: 300,
             outDuration: 300,
             constrain_width: true, // Does not change width of dropdown to that of the activator
             gutter: 0, // Spacing from edge
             hover: true, // Activate on hover
             belowOrigin: true // Displays dropdown below the button
             }
        );
      });

      var range_type = 'input[type=range]';
      var range_mousedown = false;
      var left;

      $(document).on('input mousedown touchstart', range_type, function(e) {
        var thumb = $(this).siblings('.thumb');
        var width = $(this).outerWidth();

        // If thumb indicator does not exist yet, create it
        if (thumb.length <= 0) {
          thumb = $('<span class="thumb"><span class="value"></span></span>');
          $(this).after(thumb);
        }

        // Set indicator value
        thumb.find('.value').html($(this).val());

        range_mousedown = true;
        $(this).addClass('active');

        if (!thumb.hasClass('active')) {
          thumb.velocity({ height: "60px", width: "60px", top: "-20px", marginLeft: "-15px"}, { duration: 300, easing: 'easeOutExpo' });
        }

        if (e.type !== 'input') {
          if(e.pageX === undefined || e.pageX === null){//mobile
             left = e.originalEvent.touches[0].pageX - $(this).offset().left;
          }
          else{ // desktop
             left = e.pageX - $(this).offset().left;
          }
          if (left < 0) {
            left = 0;
          }
          else if (left > width) {
            left = width;
          }
          thumb.addClass('active').css('left', left);
        }

        thumb.find('.value').html($(this).val());
      });

      $(document).on('mousemove touchmove', range_wrapper, function(e) {
        var thumb = $(this).children('.thumb');
        var left;
        if (range_mousedown) {
          if (!thumb.hasClass('active')) {
            thumb.velocity({ height: '60px', width: '60px', top: '-20px', marginLeft: '-15px'}, { duration: 300, easing: 'easeOutExpo' });
          }
          if (e.pageX === undefined || e.pageX === null) { //mobile
            left = e.originalEvent.touches[0].pageX - $(this).offset().left;
          }
          else{ // desktop
            left = e.pageX - $(this).offset().left;
          }
          var width = $(this).outerWidth();

          if (left < 0) {
            left = 0;
          }
          else if (left > width) {
            left = width;
          }
          thumb.addClass('active').css('left', left);
          thumb.find('.value').html(thumb.siblings(range_type).val());
        }
      });


	  </script>

</html>

app/views/pages/adria.html.erb
<iframe scrolling="no" src="https://www.apex-timing.com/live-timing/adria-karting/index.html#live" width="100%" height="91%">
  <p>Il tuo browser non è supportato</p>
</iframe>

app/views/pages/ficr.html.erb
<iframe src="http://livetiming.ficr.it/" width="100%" style="position: absolute; height: 91%; border: none">
  <p>Il tuo browser non è supportato</p>
</iframe>

app/views/pages/home.html.erb
<div class="row center container">
  <div class="row">

    <%= link_to pages_livetiming_path do %>
      <div id="card2rows" class="col s6">

        <div class="card small">
          <div class="card-image">
            <%= image_tag("livetiming-kart.jpg", :alt => "Livetiming Kart") %>
          </div>
          <div class="card-content">
            <h3 class ="rid row2 light-blue-text text-darken-3">Live Timing</h3>
          </div>
        </div>      

      </div>
    <% end %>

    <%= link_to pages_miscela_path do %>
      <div id="card2rows" class="col s6">

        <div class="card small">
          <div class="card-image">
            <%= image_tag("calcolo-miscela.jpg", :alt => "Calcolo della miscela") %>
          </div>
          <div class="card-content">
            <h3 class ="rid row2 light-blue-text text-darken-3">Calcolo Miscela</h3>
          </div>
        </div>

      </div>
    <% end %>

    <%= link_to pages_rapporti_path do %>
      <div id="card2rows" class="col s6">

        <div class="card small">
          <div class="card-image">
            <%= image_tag("rapporti-kart.jpg", :alt => "Rapporti Kart") %>
          </div>
          <div class="card-content">
            <h3 class ="rid row2 light-blue-text text-darken-3">Calcolo Rapporti</h3>
          </div>
        </div>

      </div>
    <% end %>

    <%= link_to tracks_path do %>
      <div id="card2rows" class="col s6">

        <div class="card small">
          <div class="card-image">
            <%= image_tag("livetiming-meteo.png", :alt => "Meteo") %>
          </div>
          <div class="card-content">
            <h3 class ="rid row2 light-blue-text text-darken-3">Live Meteo</h3>
          </div>
        </div>

      </div>
    <% end %>

  </div>
</div>

app/views/pages/livetiming.html.erb
<div class="row center container">
	<div class="row">

	    <%= link_to pages_adria_path do %>
	      <div id="time_services" class="col s6">

	        <div class="card small">
	          <div class="card-image">
	            <%= image_tag("livetiming-adria.png", :alt => "Livetiming Adria") %>
	          </div>
	          <div class="card-content">
	            <h3 class ="rid light-blue-text text-darken-3">Adria</h3>
	          </div>
	        </div>

	      </div>
	    <% end %>

	    <%= link_to pages_sgk_path do %>
	      <div id="time_services" class="col s6">

	        <div class="card small">
	          <div class="card-image">
	            <%= image_tag("livetiming-lonato.jpg", :alt => "Livetiming Lonato") %>
	          </div>
	          <div class="card-content">
	            <h3 class ="rid light-blue-text text-darken-3">Lonato</h3>
	          </div>
	        </div>

	      </div>
	    <% end %>

	    <!-- Non carica l'IFRAME con http, serve https. Contattare Ficr
	    <%= link_to pages_ficr_path do %>
	      <div id="time_services" class="col s12">

	        <div class="card medium">
	          <div class="card-image">
	            <%= image_tag('livetiming-ficr.png', :alt => 'Livetiming FICR') %>
	          </div>
	          <div class="card-content">
	            <h3 class ="rid light-blue-text text-darken-3">Federazione Italiana Cronometristi</h3>
	          </div>
	        </div>      

	      </div>
	    <% end %>
		-->

	</div>
</div>

app/views/pages/miscela.html.erb
<head>

	<script>
	  function misc() {
	    var litri = document.getElementById("litri").value;
	    var perc = document.getElementById("perc").value;
	    var olio = litri * perc * 10;
	    return olio;
	  }
	</script>

</head>

<div class="container center" id="form">

	<form name="calculator">
		<div>
			<h4>QUANTITA' DI BENZINA [l]</h4>
		    <p class="range-field">
		      <input type="range" id="litri" min="0.5" max="25" step="0.5" onChange="misc()" />
		    </p>
		    <br>
		</div>
		<div>
		    <h4 calss="center">PERCENTUALE MISCELA:</h4>
		    <p class="range-field">
		      <input type="range" id="perc" min="2" max="6" onChange="misc()" />
		    </p>
		    <br>
		</div>
		<div class="row">
			<div class="col s12 m12 l6">
		    	<h4>QUANTITA' DI OLIO [ml]</h4>
			</div>
			<div class="col s12 m12 l6">
		    	<input disabled class="center" type="text" name="ans" value="">
			</div>
		</div>
		<br>
		<a class="waves-effect waves-light btn-large btn-calc" value="Calcola" onClick="document.calculator.ans.value=misc()">CALCOLA</a>
  	</form>
        
</div>

app/views/pages/sgk.html.erb
<iframe scrolling="no" src="https://www.apex-timing.com/live-timing/southgardakarting/index.html#live" width="100%" height="91%">
  <p>Il tuo browser non è supportato</p>
</iframe>

app/views/tracks/_Adria.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/50/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Arce.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/293/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Castelletto.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/1687/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Lignano.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/5540/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Lonato.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/3647/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Martinafranca.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/3899/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Matera.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/3955/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Rieti.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/5730/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Turi.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/7510/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Ugento.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/7521/ffffff/0074c2/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_Viterbo.html.erb
<iframe class="short" scrolling="no" src="https://www.3bmeteo.com/moduli_esterni/localita_7_giorni_orario/8004/ffffff/0076c0/5e5e5e/ffffff/it" width=382 height=455 frameborder="0"></iframe>

app/views/tracks/_form.html.erb
<%= form_for @track, html: { multipart: true } do |f| %>
  <% if track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% track.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>

  <div class="field">
    <%= f.label :region %>
    <%= f.text_field :region %>
  </div>

  <div class="field">
    <%= f.label :zone %>
    <%= f.text_field :zone %>
  </div>

  <div class="field">
    <%= f.label :mag_band %>
    <%= f.number_field :mag_band %>
  </div>

  <div class="field">
    <%= f.label :length %>
    <%= f.number_field :length %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/index.html.erb
<script>
  function show() {
    var table = document.getElementById('tracciati_filtrati');

    table.style.display = 'block';
  }
</script>

<div class="container">

<%= form_tag(tracks_path, :method => "get", id: "search-form") do %>
  <div class="row">
    <div class="input_field col s12 l10">
      <%= select_tag(:search, options_for_select([['Nord', 'nord'], ['Centro', 'centro'], ['Sud', 'sud']]), {prompt: 'Mostra tutti i tracciati'}) %>
    </div>
      <%= submit_tag "Filtra", :onclick => "return show();", class: "form_submit col s12 l2 waves-effect waves-light btn src-btn" %>
  </div>
<% end %>

  <p id="notice"><%= notice %></p>

  <div class="row" id="tracciati_filtrati">

    <% @tracks.each do |track| %>

      <%= link_to track do %>

        <div id="circuit" class="col s6 center">

          <div class="card small">
            <div class="card-image">
              <%= image_tag (track.city + ".jpg"), size: "450x425" %>
            </div>
            <div class="card-content">
              <h4 class ="row2 light-blue-text text-darken-3"><%= track.name %> di <%= track.city %></h4>
            </div>
          </div>      

        </div>

      <% end %>

    <% end %>

  </div>

<% if admin_signed_in? %>

  <h1>Tracks</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>City</th>
        <th>Address</th>
        <th>Region</th>
        <th>Zone</th>
        <th>Mag band</th>
        <th>Length</th>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tracks.each do |track| %>
        <tr>
          <td><%= track.name %></td>
          <td><%= track.city %></td>
          <td><%= track.address %></td>
          <td><%= track.region %></td>
          <td><%= track.zone %></td>
          <td><%= track.mag_band %></td>
          <td><%= track.length %></td>
          <td><%= track.description %></td>
          <td><%= link_to 'Show', track %></td>
          <td><%= link_to 'Edit', edit_track_path(track) %></td>
          <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Track', new_track_path %>

<% end %>

</div>

app/views/tracks/new.html.erb
<div class="container">

	<h1>New Track</h1>

	<%= render 'form', track: @track %>

	<%= link_to 'Back', tracks_path %>

</div>